[project]
name = "linode-firewall-sync"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "linode-api4>=5.33.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
]
